name: Build

on:
  push:
    branches: [ "main" ]
    tags: [ '*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13]
        c_compiler: [clang-15, clang, emcc]
        cxx_compiler: [clang++-15, clang++, em++]
        cmake: [cmake, "emmake cmake"]
        exclude:
          - os: ubuntu-22.04
          - os: macos-13
        include:
          - os: ubuntu-22.04
            c_compiler: clang-15
            cxx_compiler: clang++-15
            cmake: cmake
          - os: macos-13
            c_compiler: clang
            cxx_compiler: clang++
            cmake: cmake
          - os: ubuntu-22.04
            c_compiler: emcc
            cxx_compiler: em++
            cmake: "emmake cmake"

    steps:
    - uses: actions/checkout@v4
    
    - name: Set VCPKG_INSTALLATION_ROOT
      run: echo "VCPKG_INSTALLATION_ROOT=${VCPKG_INSTALLATION_ROOT}" >> $GITHUB_ENV

    - name: Set VERSION
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        VERSION_WITH_PREFIX=${{ github.ref_name }}
        echo "VERSION=${VERSION_WITH_PREFIX:1}" >> $GITHUB_ENV

    - name: Cache Packages
      uses: actions/cache@v4
      with:
        path: ${{ env.VCPKG_INSTALLATION_ROOT }}
        key: ${{ runner.os }}-${{ hashFiles('vcpkg.json') }}-${{ matrix.c_compiler }}

    - name: Install Emscripten
      if: matrix.c_compiler == 'emcc'
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 3.1.51
        actions-cache-folder: 'emsdk-cache'

    - name: Configure
      run: >
        ${{ matrix.cmake }} 
        --toolchain=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake
        -B build
        -DWASM=${{ matrix.c_compiler == 'emcc' }}
        -S .
      env:
        CMAKE_BUILD_TYPE: Release
        CC: ${{ matrix.c_compiler }}
        CXX: ${{ matrix.cxx_compiler }}
        
    - name: Build
      run: |
        ${{ matrix.cmake }} --build build -j 4

    - name: Unit Test
      if: matrix.c_compiler != 'emcc'
      run: ${{ matrix.cmake }} --build build -t test
      env:
        SDL_AUDIODRIVER: dummy
        SDL_VIDEODRIVER: dummy

    - name: Package
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        ${{ matrix.cmake }} --build build -t package

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: build/latebit-*
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref_name }}
        fail_on_unmatched_files: falsebuild
