name: Build

on:
  push:
    branches: [ "main" ]
    tags: [ '*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13]
        c_compiler: [clang-15, clang]
        cxx_compiler: [clang++-15, clang++]
        exclude:
          - os: ubuntu-22.04
          - os: macos-13
        include:
          - os: ubuntu-22.04
            c_compiler: clang-15
            cxx_compiler: clang++-15
          - os: macos-13
            c_compiler: clang
            cxx_compiler: clang++

    env:
      VCPKG_ENABLE_METRICS: 0

    steps:
    - uses: actions/checkout@v4
    
    - name: Set VCPKG_INSTALLATION_ROOT
      run: echo "VCPKG_INSTALLATION_ROOT=${VCPKG_INSTALLATION_ROOT}" >> $GITHUB_ENV

    - name: Set VERSION
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        VERSION_WITH_PREFIX=${{ github.ref_name }}
        echo "VERSION=${VERSION_WITH_PREFIX:1}" >> $GITHUB_ENV

    - name: Cache Packages
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/vcpkg
        key: ${{ runner.os }}-${{ hashFiles('vcpkg.json') }}-${{ matrix.c_compiler }}

    - name: Install System Dependencies (Linux)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt update
        sudo apt-get install build-essential git make \
          pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
          libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
          libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev \
          libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
          libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev \
          libpipewire-0.3-dev libwayland-dev libdecor-0-dev -y

    - name: Install vcpkg
      if: matrix.c_compiler != 'emcc'
      uses: lukka/run-vcpkg@v11

    - name: Configure
      run: >
        cmake
        --toolchain=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake
        -B build
        -S .
      env:
        CMAKE_BUILD_TYPE: Release
        CC: ${{ matrix.c_compiler }}
        CXX: ${{ matrix.cxx_compiler }}
        
    - name: Build
      run: |
        cmake --build build -j8

    - name: Unit Test
      if: matrix.c_compiler != 'emcc'
      working-directory: build
      run: ctest -j8 --output-on-failure
      env:
        SDL_AUDIODRIVER: dummy
        SDL_VIDEODRIVER: dummy

    - name: Package
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cmake --build build -j8 -t package

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: build/latebit-*
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref_name }}
        fail_on_unmatched_files: falsebuild

  wasm:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Set VERSION
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        VERSION_WITH_PREFIX=${{ github.ref_name }}
        echo "VERSION=${VERSION_WITH_PREFIX:1}" >> $GITHUB_ENV

    - name: Install Emscripten
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 3.1.51
        actions-cache-folder: 'emsdk-cache'

    - name: Configure
      run: >
        emcmake cmake -B build
      env:
        CMAKE_BUILD_TYPE: Release

    - name: Package
      run: emmake cmake --build build -j8 -t package

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: build/latebit-*
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref_name }}
        fail_on_unmatched_files: falsebuild