name: Build

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      _VCPKG_: ${{ github.workspace }}/vcpkg
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg/bincache
      VCPKG_BINARY_SOURCES: 'clear;x-gha,readwrite'

    steps:
    - uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
    
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        if ! command -v clang++-17 &> /dev/null
        then
            wget https://apt.llvm.org/llvm.sh
            chmod +x ./llvm.sh
            sudo ./llvm.sh 17
        fi
    
    - name: run-vcpkg
      uses: lukka/run-vcpkg@v11.5

    - name: Install dependencies
      run: vcpkg install

    - name: Configure and Build
      run: |
        cmake --toolchain=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake -B build .
        cmake --build build
      env:
        CC: clang-17
        CXX: clang++-17

    - name: Lint
      run: |
        cmake --build build --target format
        cmake --build build --target tidy
      env:
        CC: clang-17
        CXX: clang++-17

    - name: Test
      run: SDL_AUDIODRIVER=dummy SDL_VIDEODRIVER=dummy ./build/test
