name: Lint, Test, and Build

on:
  push:
    branches: [ "main" ]
    tags: [ '*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13]
        c_compiler: [clang-15, clang]
        include:
          - os: ubuntu-22.04
            c_compiler: clang-15
          - os: macos-13
            c_compiler: clang
        exclude:
          - os: ubuntu-22.04
            c_compiler: clang
          - os: macos-13
            c_compiler: clang-15

    steps:
    - name: Cache Packages
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/vcpkg
        key: ${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
    
    - uses: actions/checkout@v4

    - name: run-vcpkg
      uses: lukka/run-vcpkg@v11

    - name: Configure
      run: >
        cmake 
        --toolchain=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -B build
      env:
        CC: ${{ matrix.c_compiler }}
        
    - name: Build
      run: cmake --build build

    # - name: Lint
    #   run: |
    #     cmake --build build --target format
    #     cmake --build build --target tidy

    - name: Test
      run: SDL_AUDIODRIVER=dummy SDL_VIDEODRIVER=dummy cmake --build build --target test
